apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-prometheus-access
subjects:
- kind: ServiceAccount
  name: default  # Le service account par défaut
  namespace: default  # Changez ce champ si le service account est dans un autre namespace
roleRef:
  kind: ClusterRole
  name: prometheus-access  # Le nom du rôle créé précédemment
  apiGroup: rbac.authorization.k8s.io
