apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: default  # Utilisation du namespace par défaut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-state-metrics
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      containers:
        - name: kube-state-metrics
          image: quay.io/coreos/kube-state-metrics:v1.9.7
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: default  # Utilisation du namespace par défaut
spec:
  ports:
    - port: 9091  # Le nouveau port
      targetPort: 8081  # Le port interne utilisé par le container
      protocol: TCP
  selector:
    app: kube-state-metrics
