apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-redis
  labels:
    app: node-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-redis
  template:
    metadata:
      labels:
        app: node-redis
    spec:
      containers:
        - name: node-redis
          image: redis-node-server
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
            - name: REDIS_URL
              value: redis://redis:6379
            - name: REDIS_REPLICAS_URL
              value: redis://redis-replicas:6379
          resources:
            requests:
              cpu: "100m"  # Demande minimale de CPU (100 milliCPU = 0.1 CPU)
            limits:
              cpu: "500m"  # Limite maximale de CPU (500 milliCPU = 0.5 CPU)
