apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "100m"  # Demande minimale de CPU (100 milliCPU = 0.1 CPU)
            limits:
              cpu: "500m"  # Limite maximale de CPU (500 milliCPU = 0.5 CPU)
