apiVersion: v1
kind: ServiceAccount
metadata:
  name: default  # Utilisation du service account par défaut
  namespace: default  # Changez ce champ si le service account est dans un autre namespace
  annotations:
    rbac.authorization.k8s.io/clusterrole: "prometheus-access"  # Assurez-vous que le service account a le rôle
