{
 "title": "kubernetes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Nombre de containers démarrés",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kubelet_started_containers_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre total d'erreurs lors des opérations de reconstruction des volumes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(reconstruct_volume_operations_errors_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Espace utilisé pour les logs des containers sur le système de fichiers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(kubelet_container_log_filesystem_used_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre total de containers éphémères gérés par le Kubelet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(kubelet_managed_ephemeral_containers)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre total de containers en cours d'exécution sur le nœud",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(kubelet_running_containers)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre total de containers démarrés sur les 5 dernières minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(kubelet_started_containers_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Somme des containers par pod sur les 5 dernières minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(kubelet_containers_per_pod_count_sum[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre total de containers par pod sur les 5 dernières minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(kubelet_containers_per_pod_count_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}