{
 "title": "Nodejs",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Latence des requêtes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (node-redis)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"node-redis.*\", container!=\"POD\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (node-redis)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"node-redis.*\", container!=\"POD\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilisé",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"nodejs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mémoire utilisée",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"nodejs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de requêtes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "http_requests_total{job=\"nodejs\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}