{
 "title": "Redis",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Mémoire utilisée",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{job=\"redis\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Suivi d'activité",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "redis_commands_processed_total{job=\"redis\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nbre de clients  connectés",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "redis_connected_clients{job=\"redis\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}